Algoritmo "numeroSucessor

// Disciplina  : [Lógica de Programação com JavaScript]

// Professor   : Jailson Santos

// Descrição   : Solicita um número e mostra seu sucessor

// Autor(a)    : Allan Nunes

// Data atual  : 09/09/2022

var

   numero : inteiro
   
   sucessor:inteiro


Inicio

      escreval("Digite um número: ")
      
      leia(numero)
      
      sucessor <- numero + 1
      
      escreval("O sucessor é: ", sucessor)


Fimalgoritmo