Algoritmo "numeroAntecessor

// Disciplina  : [Lógica de Programação com JavaScript]

// Professor   : Jailson Santos

// Descrição   : Solicita um número e mostra seu antecessor

// Autor(a)    : Allan Nunes

// Data atual  : 09/09/2022

var

   numero : inteiro

   antecessor:inteiro


Inicio

      escreval("Digite um número: ")

      leia(numero)

      antecessor <- numero - 1

      escreval("O antecessor é: ", antecessor)


Fimalgoritmo