Algoritmo "areaQuadrado"

// Disciplina  : [Lógica de Programação com JavaScript]

// Professor   : Jailson Santos

// Descrição   : Solicita os dois lados e exibe a área do quadrado

// Autor(a)    : Allan Nunes

// Data atual  : 09/09/2022

var

   lado: inteiro
   
   area: real

Inicio

      escreval("Digite um lado: ")

      leia(lado)

      area <- lado^2

      escreval("A área do quadrado é: ", area)


Fimalgoritmo