Algoritmo "areaCirculo"

// Disciplina  : [Lógica de Programação com JavaScript]

// Professor   : Jailson Santos

// Descrição   : Solicita o raio e exibe a área do circulo

// Autor(a)    : Allan Nunes

// Data atual  : 09/09/2022

var

   raio: inteiro

   area: real

Inicio

      escreval("Digite o raio: ")

      leia(raio)

      area <- (raio^2)*3.14

      escreval("A área do circulo é: ", area)


Fimalgoritmo